os:
    - Visual Studio 2015

build:
    verbosity: detailed

environment:
    PYTHON: C:/Python27
    PYTHON_EXECUTABLE_32: C:/Python27/python.exe
    PYTHON_EXECUTABLE_64: C:/Python27-x64/python.exe
    BOOST_ROOT: C:/Libraries/boost_1_63_0 
    USE_MSVC_RUNTIME_LIBRARY_DLL: OFF 
    VOSIMLIB_SHARED: OFF 
    VOSIMSYNTH_BUILD_VST: ON
    BUILD_SHARED_LIBS: OFF 

    matrix:
        - GENERATOR: "Visual Studio 14 2015"
          CONFIG: Debug

        - GENERATOR: "Visual Studio 14 2015"
          CONFIG: Release

        - GENERATOR: "Visual Studio 14 2015 Win64"
          CONFIG: Debug

        - GENERATOR: "Visual Studio 14 2015 Win64"
          CONFIG: Release

install:
    - git submodule update --init --recursive
    - "SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%"
    - pip install numpy
    - pip install scipy

before_build:
    - mkdir _build
    - cd _build
    - cmake .. -G "%GENERATOR%"

build_script:
    - cmake --build . --config "%CONFIG%"
