image: Visual Studio 2017

build:
    verbosity: detailed

environment:
    PYTHON_EXECUTABLE_32: C:/Miniconda/python.exe
    PYTHON_EXECUTABLE_64: C:/Miniconda-x64/python.exe
    BOOST_ROOT: C:/Libraries/boost_1_65_1
    VOSIMLIB_BUILD_PYTHON: ON
    VOSIMSYNTH_BUILD_STANDALONE: OFF
    VOSIMPROJECT_BUILD_TESTS: ON
    VOSIMPROJECT_BUILD_BENCHMARKS: ON
    VOSIMLIB_SHARED: OFF
    BUILD_SHARED_LIBS: OFF

    matrix:
        - GENERATOR: "Visual Studio 15 2017"
          CONFIG: Debug
          PYTHON: C:/Miniconda
          ARCH: x86
          BUILD_DIR: _build32

        - GENERATOR: "Visual Studio 15 2017"
          CONFIG: Release
          PYTHON: C:/Miniconda
          BUILD_DIR: _build32

        - GENERATOR: "Visual Studio 15 2017 Win64"
          CONFIG: Debug
          PYTHON: C:/Miniconda-x64
          BUILD_DIR: _build64-sse2
          VOSIMPROJECT_EIS: SSE2

        - GENERATOR: "Visual Studio 15 2017 Win64"
          CONFIG: Release
          PYTHON: C:/Miniconda-x64
          BUILD_DIR: _build64-sse2
          VOSIMPROJECT_EIS: SSE2

        - GENERATOR: "Visual Studio 15 2017 Win64"
          CONFIG: Debug
          PYTHON: C:/Miniconda-x64
          BUILD_DIR: _build64-avx2
          VOSIMPROJECT_EIS: AVX2

        - GENERATOR: "Visual Studio 15 2017 Win64"
          CONFIG: Release
          PYTHON: C:/Miniconda-x64
          BUILD_DIR: _build64-avx2
          VOSIMPROJECT_EIS: AVX2

install:
    - git submodule update --init --recursive
    - SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
    - conda update -y conda
    - conda install -y numpy scipy

before_build:
    - pushd VOSIMLib && python genTables.py -v && popd
    - mkdir %BUILD_DIR% && cd %BUILD_DIR%
    - cmake .. -G "%GENERATOR%"

build_script:
    - set
    - cd
    - cmake --build . --config "%CONFIG%"

after_build:
    - VOSIMLib\bench\%CONFIG%\vosimlib_bench.exe -r csv -o vosimlib_bench_results_%CONFIG%.csv

test_script:
    - ctest -j 2 -C %CONFIG% --output-on-failure

artifacts:
  - path: '%BUILD_DIR%/VOSIMSynth/%CONFIG%/*.dll'
    name: 'VST'
  - path: '%BUILD_DIR%/VOSIMLib/%CONFIG%/*.pyd'
    name: 'Python Bindings'
  - path: '%BUILD_DIR%/vosimlib_bench_results_%CONFIG%.csv'
    name: 'VOSIMLib benchmark'
