os:
  - Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 2017"
      CONFIG: Release

    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release

install:
    - git submodule update --init --recursive

before_build:
    - mkdir _build
    - cd _build
    - cmake .. -G "%GENERATOR%" 
    - cmake -D BUILD_SHARED_LIBS:BOOL=OFF
    - cmake -D PYTHON_EXECUTABLE_32:PATH=C:/Python27
    - cmake -D PYTHON_EXECUTABLE_64:PATH=C:/Python27-x64
    - cmake -D Boost_INCLUDE_DIR:PATH=C:/Libraries/boost_1_63_0
    - cmake -D USE_MSVC_RUNTIME_LIBRARY_DLL:BOOL=OFF
    - cmake -D VOSIMLIB_SHARED:BOOL=OFF
    - cmake -D VOSIMSYNTH_BUILD_VST:BOOL=ON

build_script:
    - cmake --build . --config "%CONFIG%"
