// This is a list of icon codes for the entypo.ttf font

#ifndef __ENTYPO__
#define __ENTYPO__

#define ENTYPO_PHONE                0x1F4DE
#define ENTYPO_MOBILE               0x1F4F1
#define ENTYPO_MOUSE                0xE789
#define ENTYPO_ADDRESS              0xE723
#define ENTYPO_MAIL                 0x2709
#define ENTYPO_PAPER_PLANE          0x1F53F
#define ENTYPO_PENCIL               0x270E
#define ENTYPO_FEATHER              0x2712
#define ENTYPO_ATTACH               0x1F4CE
#define ENTYPO_INBOX                0xE777
#define ENTYPO_REPLY                0xE712
#define ENTYPO_REPLY_ALL            0xE713
#define ENTYPO_FORWARD              0x27A6
#define ENTYPO_USER                 0x1F464
#define ENTYPO_USERS                0x1F465
#define ENTYPO_ADD_USER             0xE700
#define ENTYPO_VCARD                0xE722
#define ENTYPO_EXPORT               0xE715
#define ENTYPO_LOCATION             0xE724
#define ENTYPO_MAP                  0xE727
#define ENTYPO_COMPASS              0xE728
#define ENTYPO_DIRECTION            0x27A2
#define ENTYPO_HAIR_CROSS           0x1F3AF
#define ENTYPO_SHARE                0xE73C
#define ENTYPO_SHAREABLE            0xE73E
#define ENTYPO_HEART                0x2665
#define ENTYPO_HEART_EMPTY          0x2661
#define ENTYPO_STAR                 0x2605
#define ENTYPO_STAR_EMPTY           0x2606
#define ENTYPO_THUMBS_UP            0x1F44D
#define ENTYPO_THUMBS_DOWN          0x1F44E
#define ENTYPO_CHAT                 0xE720
#define ENTYPO_COMMENT              0xE718
#define ENTYPO_QUOTE                0x275E
#define ENTYPO_HOME                 0x2302
#define ENTYPO_POPUP                0xE74C
#define ENTYPO_SEARCH               0x1F50D
#define ENTYPO_FLASHLIGHT           0x1F526
#define ENTYPO_PRINT                0xE716
#define ENTYPO_BELL                 0x1F514
#define ENTYPO_LINK                 0x1F517
#define ENTYPO_FLAG                 0x2691
#define ENTYPO_COG                  0x2699
#define ENTYPO_TOOLS                0x2692
#define ENTYPO_TROPHY               0x1F3C6
#define ENTYPO_TAG                  0xE70C
#define ENTYPO_CAMERA               0x1F4F7
#define ENTYPO_MEGAPHONE            0x1F4E3
#define ENTYPO_MOON                 0x263D
#define ENTYPO_PALETTE              0x1F3A8
#define ENTYPO_LEAF                 0x1F342
#define ENTYPO_NOTE                 0x266A
#define ENTYPO_BEAMED_NOTE          0x266B
#define ENTYPO_NEW                  0x1F4A5
#define ENTYPO_GRADUATION_CAP       0x1F393
#define ENTYPO_BOOK                 0x1F4D5
#define ENTYPO_NEWSPAPER            0x1F4F0
#define ENTYPO_BAG                  0x1F45C
#define ENTYPO_AIRPLANE             0x2708
#define ENTYPO_LIFEBUOY             0xE788
#define ENTYPO_EYE                  0xE70A
#define ENTYPO_CLOCK                0x1F554
#define ENTYPO_MIC                  0x1F3A4
#define ENTYPO_CALENDAR             0x1F4C5
#define ENTYPO_FLASH                0x26A1
#define ENTYPO_THUNDER_CLOUD        0x26C8
#define ENTYPO_DROPLET              0x1F4A7
#define ENTYPO_CD                   0x1F4BF
#define ENTYPO_BRIEFCASE            0x1F4BC
#define ENTYPO_AIR                  0x1F4A8
#define ENTYPO_HOURGLASS            0x23F3
#define ENTYPO_GAUGE                0x1F6C7
#define ENTYPO_LANGUAGE             0x1F394
#define ENTYPO_NETWORK              0xE776
#define ENTYPO_KEY                  0x1F511
#define ENTYPO_BATTERY              0x1F50B
#define ENTYPO_BUCKET               0x1F4FE
#define ENTYPO_MAGNET               0xE7A1
#define ENTYPO_DRIVE                0x1F4FD
#define ENTYPO_CUP                  0x2615
#define ENTYPO_ROCKET               0x1F680
#define ENTYPO_BRUSH                0xE79A
#define ENTYPO_SUITCASE             0x1F6C6
#define ENTYPO_TRAFFIC_CONE         0x1F6C8
#define ENTYPO_GLOBE                0x1F30E
#define ENTYPO_KEYBOARD             0x2328
#define ENTYPO_BROWSER              0xE74E
#define ENTYPO_PUBLISH              0xE74D
#define ENTYPO_PROGRESS_3           0xE76B
#define ENTYPO_PROGRESS_2           0xE76A
#define ENTYPO_PROGRESS_1           0xE769
#define ENTYPO_PROGRESS_0           0xE768
#define ENTYPO_LIGHT_DOWN           0x1F505
#define ENTYPO_LIGHT_UP             0x1F506
#define ENTYPO_ADJUST               0x25D1
#define ENTYPO_CODE                 0xE714
#define ENTYPO_MONITOR              0x1F4BB
#define ENTYPO_INFINITY             0x221E
#define ENTYPO_LIGHT_BULB           0x1F4A1
#define ENTYPO_CREDIT_CARD          0x1F4B3
#define ENTYPO_DATABASE             0x1F4F8
#define ENTYPO_VOICEMAIL            0x2707
#define ENTYPO_CLIPBOARD            0x1F4CB
#define ENTYPO_CART                 0xE73D
#define ENTYPO_BOX                  0x1F4E6
#define ENTYPO_TICKET               0x1F3AB
#define ENTYPO_RSS                  0xE73A
#define ENTYPO_SIGNAL               0x1F4F6
#define ENTYPO_THERMOMETER          0x1F4FF
#define ENTYPO_WATER                0x1F4A6
#define ENTYPO_SWEDEN               0xF601
#define ENTYPO_LINE_GRAPH           0x1F4C8
#define ENTYPO_PIE_CHART            0x25F4
#define ENTYPO_BAR_GRAPH            0x1F4CA
#define ENTYPO_AREA_GRAPH           0x1F53E
#define ENTYPO_LOCK                 0x1F512
#define ENTYPO_LOCK_OPEN            0x1F513
#define ENTYPO_LOGOUT               0xE741
#define ENTYPO_LOGIN                0xE740
#define ENTYPO_CHECK                0x2713
#define ENTYPO_CROSS                0x274C
#define ENTYPO_SQUARED_MINUS        0x229F
#define ENTYPO_SQUARED_PLUS         0x229E
#define ENTYPO_SQUARED_CROSS        0x274E
#define ENTYPO_CIRCLED_MINUS        0x2296
#define ENTYPO_CIRCLED_PLUS         0x2295
#define ENTYPO_CIRCLED_CROSS        0x2716
#define ENTYPO_MINUS                0x2796
#define ENTYPO_PLUS                 0x2795
#define ENTYPO_ERASE                0x232B
#define ENTYPO_BLOCK                0x1F6AB
#define ENTYPO_INFO                 0x2139
#define ENTYPO_CIRCLED_INFO         0xE705
#define ENTYPO_HELP                 0x2753
#define ENTYPO_CIRCLED_HELP         0xE704
#define ENTYPO_WARNING              0x26A0
#define ENTYPO_CYCLE                0x1F504
#define ENTYPO_CW                   0x27F3
#define ENTYPO_CCW                  0x27F2
#define ENTYPO_SHUFFLE              0x1F500
#define ENTYPO_BACK                 0x1F519
#define ENTYPO_LEVEL_DOWN           0x21B3
#define ENTYPO_RETWEET              0xE717
#define ENTYPO_LOOP                 0x1F501
#define ENTYPO_BACK_IN_TIME         0xE771
#define ENTYPO_LEVEL_UP             0x21B0
#define ENTYPO_SWITCH               0x21C6
#define ENTYPO_NUMBERED_LIST        0xE005
#define ENTYPO_ADD_TO_LIST          0xE003
#define ENTYPO_LAYOUT               0x268F
#define ENTYPO_LIST                 0x2630
#define ENTYPO_TEXT_DOC             0x1F4C4
#define ENTYPO_TEXT_DOC_INVERTED    0xE731
#define ENTYPO_DOC                  0xE730
#define ENTYPO_DOCS                 0xE736
#define ENTYPO_LANDSCAPE_DOC        0xE737
#define ENTYPO_PICTURE              0x1F304
#define ENTYPO_VIDEO                0x1F3AC
#define ENTYPO_MUSIC                0x1F3B5
#define ENTYPO_FOLDER               0x1F4C1
#define ENTYPO_ARCHIVE              0xE800
#define ENTYPO_TRASH                0xE729
#define ENTYPO_UPLOAD               0x1F4E4
#define ENTYPO_DOWNLOAD             0x1F4E5
#define ENTYPO_SAVE                 0x1F4BE
#define ENTYPO_INSTALL              0xE778
#define ENTYPO_CLOUD                0x2601
#define ENTYPO_UPLOAD_CLOUD         0xE711
#define ENTYPO_BOOKMARK             0x1F516
#define ENTYPO_BOOKMARKS            0x1F4D1
#define ENTYPO_OPEN_BOOK            0x1F4D6
#define ENTYPO_PLAY                 0x25B6
#define ENTYPO_PAUS                 0x2016
#define ENTYPO_RECORD               0x25CF
#define ENTYPO_STOP                 0x25A0
#define ENTYPO_FF                   0x23E9
#define ENTYPO_FB                   0x23EA
#define ENTYPO_TO_START             0x23EE
#define ENTYPO_TO_END               0x23ED
#define ENTYPO_RESIZE_FULL          0xE744
#define ENTYPO_RESIZE_SMALL         0xE746
#define ENTYPO_VOLUME               0x23F7
#define ENTYPO_SOUND                0x1F50A
#define ENTYPO_MUTE                 0x1F507
#define ENTYPO_FLOW_CASCADE         0x1F568
#define ENTYPO_FLOW_BRANCH          0x1F569
#define ENTYPO_FLOW_TREE            0x1F56A
#define ENTYPO_FLOW_LINE            0x1F56B
#define ENTYPO_FLOW_PARALLEL        0x1F56C
#define ENTYPO_LEFT_BOLD            0xE4AD
#define ENTYPO_DOWN_BOLD            0xE4B0
#define ENTYPO_UP_BOLD              0xE4AF
#define ENTYPO_RIGHT_BOLD           0xE4AE
#define ENTYPO_LEFT                 0x2B05
#define ENTYPO_DOWN                 0x2B07
#define ENTYPO_UP                   0x2B06
#define ENTYPO_RIGHT                0x27A1
#define ENTYPO_CIRCLED_LEFT         0xE759
#define ENTYPO_CIRCLED_DOWN         0xE758
#define ENTYPO_CIRCLED_UP           0xE75B
#define ENTYPO_CIRCLED_RIGHT        0xE75A
#define ENTYPO_TRIANGLE_LEFT        0x25C2
#define ENTYPO_TRIANGLE_DOWN        0x25BE
#define ENTYPO_TRIANGLE_UP          0x25B4
#define ENTYPO_TRIANGLE_RIGHT       0x25B8
#define ENTYPO_CHEVRON_LEFT         0xE75D
#define ENTYPO_CHEVRON_DOWN         0xE75C
#define ENTYPO_CHEVRON_UP           0xE75F
#define ENTYPO_CHEVRON_RIGHT        0xE75E
#define ENTYPO_CHEVRON_SMALL_LEFT   0xE761
#define ENTYPO_CHEVRON_SMALL_DOWN   0xE760
#define ENTYPO_CHEVRON_SMALL_UP     0xE763
#define ENTYPO_CHEVRON_SMALL_RIGHT  0xE762
#define ENTYPO_CHEVRON_THIN_LEFT    0xE765
#define ENTYPO_CHEVRON_THIN_DOWN    0xE764
#define ENTYPO_CHEVRON_THIN_UP      0xE767
#define ENTYPO_CHEVRON_THIN_RIGHT   0xE766
#define ENTYPO_LEFT_THIN            0x2190
#define ENTYPO_DOWN_THIN            0x2193
#define ENTYPO_UP_THIN              0x2191
#define ENTYPO_RIGHT_THIN           0x2192
#define ENTYPO_ARROW_COMBO          0xE74F
#define ENTYPO_THREE_DOTS           0x23F6
#define ENTYPO_TWO_DOTS             0x23F5
#define ENTYPO_DOT                  0x23F4
#define ENTYPO_CC                   0x1F545
#define ENTYPO_CC_BY                0x1F546
#define ENTYPO_CC_NC                0x1F547
#define ENTYPO_CC_NC_EU             0x1F548
#define ENTYPO_CC_NC_JP             0x1F549
#define ENTYPO_CC_SA                0x1F54A
#define ENTYPO_CC_ND                0x1F54B
#define ENTYPO_CC_PD                0x1F54C
#define ENTYPO_CC_ZERO              0x1F54D
#define ENTYPO_CC_SHARE             0x1F54E
#define ENTYPO_CC_REMIX             0x1F54F
#define ENTYPO_DB_LOGO              0x1F5F9
#define ENTYPO_DB_SHAPE             0x1F5FA
#define ENTYPO_GITHUB               0xF300
#define ENTYPO_C_GITHUB             0xF301
#define ENTYPO_FLICKR               0xF303
#define ENTYPO_C_FLICKR             0xF304
#define ENTYPO_VIMEO                0xF306
#define ENTYPO_C_VIMEO              0xF307
#define ENTYPO_TWITTER              0xF309
#define ENTYPO_C_TWITTER            0xF30A
#define ENTYPO_FACEBOOK             0xF30C
#define ENTYPO_C_FACEBOOK           0xF30D
#define ENTYPO_S_FACEBOOK           0xF30E
#define ENTYPO_GOOGLEPLUS           0xF30F
#define ENTYPO_C_GOOGLEPLUS         0xF310
#define ENTYPO_PINTEREST            0xF312
#define ENTYPO_C_PINTEREST          0xF313
#define ENTYPO_TUMBLR               0xF315
#define ENTYPO_C_TUMBLR             0xF316
#define ENTYPO_LINKEDIN             0xF318
#define ENTYPO_C_LINKEDIN           0xF319
#define ENTYPO_DRIBBBLE             0xF31B
#define ENTYPO_C_DRIBBBLE           0xF31C
#define ENTYPO_STUMBLEUPON          0xF31E
#define ENTYPO_C_STUMBLEUPON        0xF31F
#define ENTYPO_LASTFM               0xF321
#define ENTYPO_C_LASTFM             0xF322
#define ENTYPO_RDIO                 0xF324
#define ENTYPO_C_RDIO               0xF325
#define ENTYPO_SPOTIFY              0xF327
#define ENTYPO_C_SPOTIFY            0xF328
#define ENTYPO_QQ                   0xF32A
#define ENTYPO_INSTAGRAM            0xF32D
#define ENTYPO_DROPBOX              0xF330
#define ENTYPO_EVERNOTE             0xF333
#define ENTYPO_FLATTR               0xF336
#define ENTYPO_SKYPE                0xF339
#define ENTYPO_C_SKYPE              0xF33A
#define ENTYPO_RENREN               0xF33C
#define ENTYPO_SINA_WEIBO           0xF33F
#define ENTYPO_PAYPAL               0xF342
#define ENTYPO_PICASA               0xF345
#define ENTYPO_SOUNDCLOUD           0xF348
#define ENTYPO_MIXI                 0xF34B
#define ENTYPO_BEHANCE              0xF34E
#define ENTYPO_GOOGLE_CIRCLES       0xF351
#define ENTYPO_VK                   0xF354
#define ENTYPO_SMASHING             0xF357

#endif /* __ENTYPO_ENTYPO_H */
